### ISSUE TITLE
Object reference not set to an instance of an object when transmission-daemon is down

### ISSUE THREAD

**Issue by mnieto** [Beatlegger/Transmission.NetCore#5]
The SendRequestAsync method throws a NullReferenceException if the server is down.
It should throw a more appropriate exception.

**Comment by Beatlegger** [comment]
Try use [Transmission.API.RPC](https://github.com/Beatlegger/Transmission.API.RPC)
**Transmission.API.RPC** - netstandart2.0 project.

**Comment by mnieto** [comment]
Ok, great to know the project is continued. Perhaps you could write a note in readme redirecting to the new project
